Ros:
  node_name: "grace_behav_exec"
  queue_size: 100
  
  #Gaze & Head gestures
  hr_people_perception_topic: "/hr/perception/people"
  hr_ATTN_cfg_server: "/hr/behavior/attention"
  hr_face_target_topic: "/hr/animation/set_face_target"
  hr_head_gesture_topic: "/hr/animation/set_animation"
  hr_nod_common_string: "nod_Short"
  final_target_person_topic: "/grace_proj/final_target_person"
  attn_timeout: 2.0

  #TTS 
  english_language_code: &id_lang_eng 'en-US' 
  cantonese_language_code: &id_lang_yue 'yue-Hant-HK' 
  tts_language_code: *id_lang_yue

  tts_data_service: "/hr/control/speech/data"
  tts_say_service: "/hr/control/speech/tts"
  tts_control_topic: "/hr/control/speech/tts_control"
  tts_event_topic: "/hr/control/speech/event"
  tts_stop_cmd: "shutup"
  tts_end_event_string: "stop"
  tts_pure_token: '|p|'

  #Arm Gestures
  arm_animation_topic: "/hr/animation/set_arm_animation"
  arm_animation_normal_length_service: "/hr/animation/get_arm_animation_length"
  arm_animation_motor_speed_reconfig: "/hr/animation/settings"

  #Expressions
  expression_topic: "/hr/animation/set_expression"

  #Control Interface
  end_of_conv_topic: "/grace_proj/stop"
  grace_behavior_service: "/grace_proj/execute_behavior_command"
  speak_event_topic: "/grace_proj/speak_event"
  nod_event_topic: "/grace_proj/nod_event"
  gaze_event_topic: "/grace_proj/gaze_event"



General:
  #Request
  comp_behav_exec_cmd: "comp_exec"
  nod_cmd: "nod"
  head_gaze_follow: "head_gaze_follow"
  head_gaze_avert: "head_gaze_avert"
  all_behav_stop_cmd: "all_stop"

  #Response
  behav_succ_string: "completed"
  behav_all_stopped_string: "stopped"

  #Event code
  start_speaking_event_name: "speaking_start"
  stop_speaking_event_name: "speaking_stop"

  start_nodding_event_name: "nodding_start"
  stop_nodding_event_name: "nodding_stop"
  
  start_following_event_name: "gaze_following"
  start_aversion_event_name: "gaze_aversion"




CompositeBehavior:
  #Composite Behavior service related commands
  comp_behav_exec_rate: 30

  Predefined:
    neutral_pose_info:
      name: "MAIN-1"
      dur: 4
      magnitude: 1.0

    neutral_expression_info:
      name: "happy"
      dur: 3
      magnitude: 0

    Sample:
      txt: "Hello, this is a test script and I will just count. 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20."
      lang: *id_lang_eng

      expressions: ['happy','fear']
      exp_start: [0.1, 0.6]
      exp_end: [0.4, 0.9]
      exp_mag: [0.8, 0.8]

      gestures: ['MAIN-OOPS','MAIN-2','MAIN-1']
      ges_start: [0.1, 0.4, 0.8]
      ges_end: [0.3, 0.5, 0.9] 
      ges_mag: [1, 1, 1] 


TTS:
  #TTS 


HeadGazeGes:
  #Nodding
  #(1-7)
  nod_type_strings: [1,7]
  #[0.25, 1.0]
  nod_mag_range: [0.25, 1.0]
  nod_dummy_dur: 0.2

  #Following & aversion
  gaze_thread_rate: 5

  follow_timeout: 2.0

  dummy_target_id: "gaze_dummy_target"
  aversion_loc_range: [0.1,0.3]
  neutral_gaze_dummy_target: [1.5, 0, 1.5, 1.0] #x-y-z-Speed
  no_target_string: "None"
  aversion_target_min_life_expand: 1.5 #Minimal living time of an aversion target
  aversion_mean_life_expand: 2.5 #Mean living time per aversion target



ArmGes:
  #Arm Gestures
  arm_anim_min_motor_transition_time: 1.0
  arm_anim_motor_transition_time: 2.0

Expressions:
  #Expressions 




